### ISSUE TITLE
Cannot Solve this configuration

### ISSUE THREAD

**Issue by NISH1001** [codingOtaku/8-puzzle#1]
0,2,3,4,5,6,7,1,8

**Comment by bglearning** [comment]
It does but takes an enormous amount of time. AST performs brilliantly. 

**_BFS_**

> path_to_goal: ['RIGHT', 'DOWN', 'RIGHT', 'UP', 'LEFT', 'LEFT', 'DOWN', 'RIGHT', 'DOWN', 'LEFT', 'UP', 'RIGHT', 'RIGHT', 'UP', 'LEFT', 'LEFT', 'DOWN', 'RIGHT', 'UP', 'LEFT']
> cost_of_path: 20
> nodes_expanded: 51505
> search_depth: 20
> max_search_depth: 21
> running_time: 1586.1269371509552
> max_ram_usage: 79.6875

**_AST_** 

> path_to_goal: ['RIGHT', 'DOWN', 'RIGHT', 'UP', 'LEFT', 'LEFT', 'DOWN', 'RIGHT', 'RIGHT', 'UP', 'LEFT', 'DOWN', 'DOWN', 'LEFT', 'UP', 'UP', 'RIGHT', 'DOWN', 'LEFT', 'UP']
> cost_of_path: 20
> nodes_expanded: 292
> search_depth: 20
> max_search_depth: 20
> running_time: 0.28322625
> max_ram_usage: 10.05078125

**Comment by NISH1001** [comment]
Oh. I thought the program was running in an infinite loop. However, the problem shouldn't have taken that much time. There must be something wrong with the algorithm
